### ISSUE TITLE
blank pdf

### ISSUE THREAD

**Issue by lorvent** [ulivz/vuepress-plugin-export#1]
Hello,
when i run the command, if has generated 21 pages of pdf but it is just empty and the file size is just 14kb.

am i missing something or plugin is still in experimental stage?

**Comment by ulivz** [comment]
Since here are some internal changes of node api in VuePress, you would get stuck in some of the transitional versions, could you check `VuePress@1.0.0-alpha.44` and `vuepress-plugin-export@0.2.0` and tell me if I close this issue?

**Comment by lorvent** [comment]
yay! it is generating so i am closing this issue.

but i found many issues

1. it has links to dev URL (localhost:800) 

2. ordering of pages is not correct

3. some text is being convered up by header part 
![image](https://user-images.githubusercontent.com/3512953/54090868-c75a7a00-439e-11e9-8972-b7316344690c.png)

i understand that, root cause of all these is using puppeteer and making screenshots into pdf,

probably we should go with some other approach like gitbook does.

**Comment by ulivz** [comment]
All the issues you mentioned can be addressed, contribution welcome!

**Comment by e0lithic** [comment]
Hi, 

I am on vuepress 1.5 and the latest version of the plugin. However, I am still getting a blank pdf even though the tool runs properly to completion. Am I missing something?

Thanks
